// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace camera {
class CaptureFormatDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CaptureFormat> {
} _CaptureFormat_default_instance_;
class CameraDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Camera> {
} _Camera_default_instance_;
class CameraListDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CameraList> {
} _CameraList_default_instance_;
class StartCaptureArgumentsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<StartCaptureArguments> {
} _StartCaptureArguments_default_instance_;
class StartCaptureResultDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<StartCaptureResult> {
} _StartCaptureResult_default_instance_;

namespace protobuf_proto_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[5];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CaptureFormat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CaptureFormat, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CaptureFormat, height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CaptureFormat, framerate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CaptureFormat, encoding_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, cameraname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, camerapath_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, formats_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraList, cameras_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureArguments, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureArguments, cameraname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureArguments, camerapath_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureArguments, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureArguments, height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureArguments, framerate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureArguments, encoding_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureResult, canresetgraph_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureResult, cansetaudioconfig_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureResult, cansetvideoconfig_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureResult, canconnectfilters_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureResult, result_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartCaptureResult, devicepointer_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CaptureFormat)},
  { 9, -1, sizeof(Camera)},
  { 17, -1, sizeof(CameraList)},
  { 23, -1, sizeof(StartCaptureArguments)},
  { 34, -1, sizeof(StartCaptureResult)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CaptureFormat_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Camera_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_CameraList_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_StartCaptureArguments_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_StartCaptureResult_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "proto.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

}  // namespace

void TableStruct::Shutdown() {
  _CaptureFormat_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Camera_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _CameraList_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _StartCaptureArguments_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
  _StartCaptureResult_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CaptureFormat_default_instance_.DefaultConstruct();
  _Camera_default_instance_.DefaultConstruct();
  _CameraList_default_instance_.DefaultConstruct();
  _StartCaptureArguments_default_instance_.DefaultConstruct();
  _StartCaptureResult_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\013proto.proto\022\006camera\"l\n\rCaptureFormat\022\r"
      "\n\005width\030\001 \001(\r\022\016\n\006height\030\002 \001(\r\022\021\n\tframera"
      "te\030\003 \001(\001\022)\n\010encoding\030\004 \001(\0162\027.camera.Capt"
      "ureEncoding\"X\n\006Camera\022\022\n\ncameraName\030\005 \001("
      "\t\022\022\n\ncameraPath\030\006 \001(\t\022&\n\007formats\030\007 \003(\0132\025"
      ".camera.CaptureFormat\"-\n\nCameraList\022\037\n\007c"
      "ameras\030\007 \003(\0132\016.camera.Camera\"\234\001\n\025StartCa"
      "ptureArguments\022\022\n\ncameraName\030\010 \001(\t\022\022\n\nca"
      "meraPath\030\t \001(\t\022\r\n\005width\030\n \001(\r\022\016\n\006height\030"
      "\013 \001(\r\022\021\n\tframerate\030\014 \001(\001\022)\n\010encoding\030\r \001"
      "(\0162\027.camera.CaptureEncoding\"\270\001\n\022StartCap"
      "tureResult\022\025\n\rcanResetGraph\030\016 \001(\010\022\031\n\021can"
      "SetAudioConfig\030\017 \001(\010\022\031\n\021canSetVideoConfi"
      "g\030\020 \001(\010\022\031\n\021canConnectFilters\030\021 \001(\010\022#\n\006re"
      "sult\030\022 \001(\0162\023.camera.StartResult\022\025\n\rdevic"
      "ePointer\030\023 \001(\004*\240\001\n\017CaptureEncoding\022\007\n\003An"
      "y\020\000\022\013\n\007Unknown\020\001\022\010\n\004ARGB\020\002\022\010\n\004XRGB\020\003\022\010\n\004"
      "I420\020\004\022\010\n\004NV12\020\005\022\010\n\004YV12\020\006\022\010\n\004Y800\020\007\022\010\n\004"
      "YVYU\020\010\022\010\n\004YUY2\020\t\022\010\n\004UYVY\020\n\022\010\n\004HDYC\020\013\022\t\n\005"
      "MJPEG\020\014\022\010\n\004H264\020\r*0\n\013StartResult\022\013\n\007Succ"
      "ess\020\000\022\t\n\005InUse\020\001\022\t\n\005Error\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 835);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_proto_2eproto

const ::google::protobuf::EnumDescriptor* CaptureEncoding_descriptor() {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_enum_descriptors[0];
}
bool CaptureEncoding_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* StartResult_descriptor() {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_enum_descriptors[1];
}
bool StartResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CaptureFormat::kWidthFieldNumber;
const int CaptureFormat::kHeightFieldNumber;
const int CaptureFormat::kFramerateFieldNumber;
const int CaptureFormat::kEncodingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CaptureFormat::CaptureFormat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_proto_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera.CaptureFormat)
}
CaptureFormat::CaptureFormat(const CaptureFormat& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&width_, &from.width_,
    reinterpret_cast<char*>(&encoding_) -
    reinterpret_cast<char*>(&width_) + sizeof(encoding_));
  // @@protoc_insertion_point(copy_constructor:camera.CaptureFormat)
}

void CaptureFormat::SharedCtor() {
  ::memset(&width_, 0, reinterpret_cast<char*>(&encoding_) -
    reinterpret_cast<char*>(&width_) + sizeof(encoding_));
  _cached_size_ = 0;
}

CaptureFormat::~CaptureFormat() {
  // @@protoc_insertion_point(destructor:camera.CaptureFormat)
  SharedDtor();
}

void CaptureFormat::SharedDtor() {
}

void CaptureFormat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CaptureFormat::descriptor() {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CaptureFormat& CaptureFormat::default_instance() {
  protobuf_proto_2eproto::InitDefaults();
  return *internal_default_instance();
}

CaptureFormat* CaptureFormat::New(::google::protobuf::Arena* arena) const {
  CaptureFormat* n = new CaptureFormat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CaptureFormat::Clear() {
// @@protoc_insertion_point(message_clear_start:camera.CaptureFormat)
  ::memset(&width_, 0, reinterpret_cast<char*>(&encoding_) -
    reinterpret_cast<char*>(&width_) + sizeof(encoding_));
}

bool CaptureFormat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera.CaptureFormat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 width = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 height = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double framerate = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &framerate_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .camera.CaptureEncoding encoding = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_encoding(static_cast< ::camera::CaptureEncoding >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera.CaptureFormat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera.CaptureFormat)
  return false;
#undef DO_
}

void CaptureFormat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera.CaptureFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 width = 1;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->width(), output);
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->height(), output);
  }

  // double framerate = 3;
  if (this->framerate() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->framerate(), output);
  }

  // .camera.CaptureEncoding encoding = 4;
  if (this->encoding() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->encoding(), output);
  }

  // @@protoc_insertion_point(serialize_end:camera.CaptureFormat)
}

::google::protobuf::uint8* CaptureFormat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:camera.CaptureFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 width = 1;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->width(), target);
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->height(), target);
  }

  // double framerate = 3;
  if (this->framerate() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->framerate(), target);
  }

  // .camera.CaptureEncoding encoding = 4;
  if (this->encoding() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->encoding(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:camera.CaptureFormat)
  return target;
}

size_t CaptureFormat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera.CaptureFormat)
  size_t total_size = 0;

  // uint32 width = 1;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width());
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->height());
  }

  // double framerate = 3;
  if (this->framerate() != 0) {
    total_size += 1 + 8;
  }

  // .camera.CaptureEncoding encoding = 4;
  if (this->encoding() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->encoding());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CaptureFormat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera.CaptureFormat)
  GOOGLE_DCHECK_NE(&from, this);
  const CaptureFormat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CaptureFormat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera.CaptureFormat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera.CaptureFormat)
    MergeFrom(*source);
  }
}

void CaptureFormat::MergeFrom(const CaptureFormat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera.CaptureFormat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.framerate() != 0) {
    set_framerate(from.framerate());
  }
  if (from.encoding() != 0) {
    set_encoding(from.encoding());
  }
}

void CaptureFormat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera.CaptureFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CaptureFormat::CopyFrom(const CaptureFormat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera.CaptureFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CaptureFormat::IsInitialized() const {
  return true;
}

void CaptureFormat::Swap(CaptureFormat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CaptureFormat::InternalSwap(CaptureFormat* other) {
  std::swap(width_, other->width_);
  std::swap(height_, other->height_);
  std::swap(framerate_, other->framerate_);
  std::swap(encoding_, other->encoding_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CaptureFormat::GetMetadata() const {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CaptureFormat

// uint32 width = 1;
void CaptureFormat::clear_width() {
  width_ = 0u;
}
::google::protobuf::uint32 CaptureFormat::width() const {
  // @@protoc_insertion_point(field_get:camera.CaptureFormat.width)
  return width_;
}
void CaptureFormat::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:camera.CaptureFormat.width)
}

// uint32 height = 2;
void CaptureFormat::clear_height() {
  height_ = 0u;
}
::google::protobuf::uint32 CaptureFormat::height() const {
  // @@protoc_insertion_point(field_get:camera.CaptureFormat.height)
  return height_;
}
void CaptureFormat::set_height(::google::protobuf::uint32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:camera.CaptureFormat.height)
}

// double framerate = 3;
void CaptureFormat::clear_framerate() {
  framerate_ = 0;
}
double CaptureFormat::framerate() const {
  // @@protoc_insertion_point(field_get:camera.CaptureFormat.framerate)
  return framerate_;
}
void CaptureFormat::set_framerate(double value) {
  
  framerate_ = value;
  // @@protoc_insertion_point(field_set:camera.CaptureFormat.framerate)
}

// .camera.CaptureEncoding encoding = 4;
void CaptureFormat::clear_encoding() {
  encoding_ = 0;
}
::camera::CaptureEncoding CaptureFormat::encoding() const {
  // @@protoc_insertion_point(field_get:camera.CaptureFormat.encoding)
  return static_cast< ::camera::CaptureEncoding >(encoding_);
}
void CaptureFormat::set_encoding(::camera::CaptureEncoding value) {
  
  encoding_ = value;
  // @@protoc_insertion_point(field_set:camera.CaptureFormat.encoding)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Camera::kCameraNameFieldNumber;
const int Camera::kCameraPathFieldNumber;
const int Camera::kFormatsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Camera::Camera()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_proto_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera.Camera)
}
Camera::Camera(const Camera& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      formats_(from.formats_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  cameraname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.cameraname().size() > 0) {
    cameraname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cameraname_);
  }
  camerapath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.camerapath().size() > 0) {
    camerapath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.camerapath_);
  }
  // @@protoc_insertion_point(copy_constructor:camera.Camera)
}

void Camera::SharedCtor() {
  cameraname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camerapath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

Camera::~Camera() {
  // @@protoc_insertion_point(destructor:camera.Camera)
  SharedDtor();
}

void Camera::SharedDtor() {
  cameraname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camerapath_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Camera::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Camera::descriptor() {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Camera& Camera::default_instance() {
  protobuf_proto_2eproto::InitDefaults();
  return *internal_default_instance();
}

Camera* Camera::New(::google::protobuf::Arena* arena) const {
  Camera* n = new Camera;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Camera::Clear() {
// @@protoc_insertion_point(message_clear_start:camera.Camera)
  formats_.Clear();
  cameraname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camerapath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Camera::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera.Camera)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string cameraName = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cameraname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cameraname().data(), this->cameraname().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "camera.Camera.cameraName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string cameraPath = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_camerapath()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->camerapath().data(), this->camerapath().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "camera.Camera.cameraPath"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .camera.CaptureFormat formats = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_formats()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera.Camera)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera.Camera)
  return false;
#undef DO_
}

void Camera::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera.Camera)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cameraName = 5;
  if (this->cameraname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cameraname().data(), this->cameraname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "camera.Camera.cameraName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->cameraname(), output);
  }

  // string cameraPath = 6;
  if (this->camerapath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->camerapath().data(), this->camerapath().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "camera.Camera.cameraPath");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->camerapath(), output);
  }

  // repeated .camera.CaptureFormat formats = 7;
  for (unsigned int i = 0, n = this->formats_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->formats(i), output);
  }

  // @@protoc_insertion_point(serialize_end:camera.Camera)
}

::google::protobuf::uint8* Camera::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:camera.Camera)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cameraName = 5;
  if (this->cameraname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cameraname().data(), this->cameraname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "camera.Camera.cameraName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->cameraname(), target);
  }

  // string cameraPath = 6;
  if (this->camerapath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->camerapath().data(), this->camerapath().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "camera.Camera.cameraPath");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->camerapath(), target);
  }

  // repeated .camera.CaptureFormat formats = 7;
  for (unsigned int i = 0, n = this->formats_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, this->formats(i), deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:camera.Camera)
  return target;
}

size_t Camera::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera.Camera)
  size_t total_size = 0;

  // repeated .camera.CaptureFormat formats = 7;
  {
    unsigned int count = this->formats_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->formats(i));
    }
  }

  // string cameraName = 5;
  if (this->cameraname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cameraname());
  }

  // string cameraPath = 6;
  if (this->camerapath().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->camerapath());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Camera::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera.Camera)
  GOOGLE_DCHECK_NE(&from, this);
  const Camera* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Camera>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera.Camera)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera.Camera)
    MergeFrom(*source);
  }
}

void Camera::MergeFrom(const Camera& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera.Camera)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  formats_.MergeFrom(from.formats_);
  if (from.cameraname().size() > 0) {

    cameraname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cameraname_);
  }
  if (from.camerapath().size() > 0) {

    camerapath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.camerapath_);
  }
}

void Camera::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera.Camera)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Camera::CopyFrom(const Camera& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera.Camera)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Camera::IsInitialized() const {
  return true;
}

void Camera::Swap(Camera* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Camera::InternalSwap(Camera* other) {
  formats_.InternalSwap(&other->formats_);
  cameraname_.Swap(&other->cameraname_);
  camerapath_.Swap(&other->camerapath_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Camera::GetMetadata() const {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Camera

// string cameraName = 5;
void Camera::clear_cameraname() {
  cameraname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Camera::cameraname() const {
  // @@protoc_insertion_point(field_get:camera.Camera.cameraName)
  return cameraname_.GetNoArena();
}
void Camera::set_cameraname(const ::std::string& value) {
  
  cameraname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:camera.Camera.cameraName)
}
#if LANG_CXX11
void Camera::set_cameraname(::std::string&& value) {
  
  cameraname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:camera.Camera.cameraName)
}
#endif
void Camera::set_cameraname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  cameraname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:camera.Camera.cameraName)
}
void Camera::set_cameraname(const char* value, size_t size) {
  
  cameraname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:camera.Camera.cameraName)
}
::std::string* Camera::mutable_cameraname() {
  
  // @@protoc_insertion_point(field_mutable:camera.Camera.cameraName)
  return cameraname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Camera::release_cameraname() {
  // @@protoc_insertion_point(field_release:camera.Camera.cameraName)
  
  return cameraname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Camera::set_allocated_cameraname(::std::string* cameraname) {
  if (cameraname != NULL) {
    
  } else {
    
  }
  cameraname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cameraname);
  // @@protoc_insertion_point(field_set_allocated:camera.Camera.cameraName)
}

// string cameraPath = 6;
void Camera::clear_camerapath() {
  camerapath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Camera::camerapath() const {
  // @@protoc_insertion_point(field_get:camera.Camera.cameraPath)
  return camerapath_.GetNoArena();
}
void Camera::set_camerapath(const ::std::string& value) {
  
  camerapath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:camera.Camera.cameraPath)
}
#if LANG_CXX11
void Camera::set_camerapath(::std::string&& value) {
  
  camerapath_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:camera.Camera.cameraPath)
}
#endif
void Camera::set_camerapath(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  camerapath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:camera.Camera.cameraPath)
}
void Camera::set_camerapath(const char* value, size_t size) {
  
  camerapath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:camera.Camera.cameraPath)
}
::std::string* Camera::mutable_camerapath() {
  
  // @@protoc_insertion_point(field_mutable:camera.Camera.cameraPath)
  return camerapath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Camera::release_camerapath() {
  // @@protoc_insertion_point(field_release:camera.Camera.cameraPath)
  
  return camerapath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Camera::set_allocated_camerapath(::std::string* camerapath) {
  if (camerapath != NULL) {
    
  } else {
    
  }
  camerapath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camerapath);
  // @@protoc_insertion_point(field_set_allocated:camera.Camera.cameraPath)
}

// repeated .camera.CaptureFormat formats = 7;
int Camera::formats_size() const {
  return formats_.size();
}
void Camera::clear_formats() {
  formats_.Clear();
}
const ::camera::CaptureFormat& Camera::formats(int index) const {
  // @@protoc_insertion_point(field_get:camera.Camera.formats)
  return formats_.Get(index);
}
::camera::CaptureFormat* Camera::mutable_formats(int index) {
  // @@protoc_insertion_point(field_mutable:camera.Camera.formats)
  return formats_.Mutable(index);
}
::camera::CaptureFormat* Camera::add_formats() {
  // @@protoc_insertion_point(field_add:camera.Camera.formats)
  return formats_.Add();
}
::google::protobuf::RepeatedPtrField< ::camera::CaptureFormat >*
Camera::mutable_formats() {
  // @@protoc_insertion_point(field_mutable_list:camera.Camera.formats)
  return &formats_;
}
const ::google::protobuf::RepeatedPtrField< ::camera::CaptureFormat >&
Camera::formats() const {
  // @@protoc_insertion_point(field_list:camera.Camera.formats)
  return formats_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CameraList::kCamerasFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CameraList::CameraList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_proto_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera.CameraList)
}
CameraList::CameraList(const CameraList& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      cameras_(from.cameras_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:camera.CameraList)
}

void CameraList::SharedCtor() {
  _cached_size_ = 0;
}

CameraList::~CameraList() {
  // @@protoc_insertion_point(destructor:camera.CameraList)
  SharedDtor();
}

void CameraList::SharedDtor() {
}

void CameraList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CameraList::descriptor() {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CameraList& CameraList::default_instance() {
  protobuf_proto_2eproto::InitDefaults();
  return *internal_default_instance();
}

CameraList* CameraList::New(::google::protobuf::Arena* arena) const {
  CameraList* n = new CameraList;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CameraList::Clear() {
// @@protoc_insertion_point(message_clear_start:camera.CameraList)
  cameras_.Clear();
}

bool CameraList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera.CameraList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .camera.Camera cameras = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_cameras()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera.CameraList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera.CameraList)
  return false;
#undef DO_
}

void CameraList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera.CameraList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .camera.Camera cameras = 7;
  for (unsigned int i = 0, n = this->cameras_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->cameras(i), output);
  }

  // @@protoc_insertion_point(serialize_end:camera.CameraList)
}

::google::protobuf::uint8* CameraList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:camera.CameraList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .camera.Camera cameras = 7;
  for (unsigned int i = 0, n = this->cameras_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, this->cameras(i), deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:camera.CameraList)
  return target;
}

size_t CameraList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera.CameraList)
  size_t total_size = 0;

  // repeated .camera.Camera cameras = 7;
  {
    unsigned int count = this->cameras_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->cameras(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CameraList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera.CameraList)
  GOOGLE_DCHECK_NE(&from, this);
  const CameraList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CameraList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera.CameraList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera.CameraList)
    MergeFrom(*source);
  }
}

void CameraList::MergeFrom(const CameraList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera.CameraList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cameras_.MergeFrom(from.cameras_);
}

void CameraList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera.CameraList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CameraList::CopyFrom(const CameraList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera.CameraList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraList::IsInitialized() const {
  return true;
}

void CameraList::Swap(CameraList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CameraList::InternalSwap(CameraList* other) {
  cameras_.InternalSwap(&other->cameras_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CameraList::GetMetadata() const {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CameraList

// repeated .camera.Camera cameras = 7;
int CameraList::cameras_size() const {
  return cameras_.size();
}
void CameraList::clear_cameras() {
  cameras_.Clear();
}
const ::camera::Camera& CameraList::cameras(int index) const {
  // @@protoc_insertion_point(field_get:camera.CameraList.cameras)
  return cameras_.Get(index);
}
::camera::Camera* CameraList::mutable_cameras(int index) {
  // @@protoc_insertion_point(field_mutable:camera.CameraList.cameras)
  return cameras_.Mutable(index);
}
::camera::Camera* CameraList::add_cameras() {
  // @@protoc_insertion_point(field_add:camera.CameraList.cameras)
  return cameras_.Add();
}
::google::protobuf::RepeatedPtrField< ::camera::Camera >*
CameraList::mutable_cameras() {
  // @@protoc_insertion_point(field_mutable_list:camera.CameraList.cameras)
  return &cameras_;
}
const ::google::protobuf::RepeatedPtrField< ::camera::Camera >&
CameraList::cameras() const {
  // @@protoc_insertion_point(field_list:camera.CameraList.cameras)
  return cameras_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StartCaptureArguments::kCameraNameFieldNumber;
const int StartCaptureArguments::kCameraPathFieldNumber;
const int StartCaptureArguments::kWidthFieldNumber;
const int StartCaptureArguments::kHeightFieldNumber;
const int StartCaptureArguments::kFramerateFieldNumber;
const int StartCaptureArguments::kEncodingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StartCaptureArguments::StartCaptureArguments()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_proto_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera.StartCaptureArguments)
}
StartCaptureArguments::StartCaptureArguments(const StartCaptureArguments& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  cameraname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.cameraname().size() > 0) {
    cameraname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cameraname_);
  }
  camerapath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.camerapath().size() > 0) {
    camerapath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.camerapath_);
  }
  ::memcpy(&encoding_, &from.encoding_,
    reinterpret_cast<char*>(&framerate_) -
    reinterpret_cast<char*>(&encoding_) + sizeof(framerate_));
  // @@protoc_insertion_point(copy_constructor:camera.StartCaptureArguments)
}

void StartCaptureArguments::SharedCtor() {
  cameraname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camerapath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&encoding_, 0, reinterpret_cast<char*>(&framerate_) -
    reinterpret_cast<char*>(&encoding_) + sizeof(framerate_));
  _cached_size_ = 0;
}

StartCaptureArguments::~StartCaptureArguments() {
  // @@protoc_insertion_point(destructor:camera.StartCaptureArguments)
  SharedDtor();
}

void StartCaptureArguments::SharedDtor() {
  cameraname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camerapath_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void StartCaptureArguments::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StartCaptureArguments::descriptor() {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StartCaptureArguments& StartCaptureArguments::default_instance() {
  protobuf_proto_2eproto::InitDefaults();
  return *internal_default_instance();
}

StartCaptureArguments* StartCaptureArguments::New(::google::protobuf::Arena* arena) const {
  StartCaptureArguments* n = new StartCaptureArguments;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StartCaptureArguments::Clear() {
// @@protoc_insertion_point(message_clear_start:camera.StartCaptureArguments)
  cameraname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camerapath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&encoding_, 0, reinterpret_cast<char*>(&framerate_) -
    reinterpret_cast<char*>(&encoding_) + sizeof(framerate_));
}

bool StartCaptureArguments::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera.StartCaptureArguments)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string cameraName = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cameraname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cameraname().data(), this->cameraname().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "camera.StartCaptureArguments.cameraName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string cameraPath = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_camerapath()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->camerapath().data(), this->camerapath().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "camera.StartCaptureArguments.cameraPath"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 width = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 height = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double framerate = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(97u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &framerate_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .camera.CaptureEncoding encoding = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(104u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_encoding(static_cast< ::camera::CaptureEncoding >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera.StartCaptureArguments)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera.StartCaptureArguments)
  return false;
#undef DO_
}

void StartCaptureArguments::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera.StartCaptureArguments)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cameraName = 8;
  if (this->cameraname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cameraname().data(), this->cameraname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "camera.StartCaptureArguments.cameraName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->cameraname(), output);
  }

  // string cameraPath = 9;
  if (this->camerapath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->camerapath().data(), this->camerapath().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "camera.StartCaptureArguments.cameraPath");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->camerapath(), output);
  }

  // uint32 width = 10;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->width(), output);
  }

  // uint32 height = 11;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(11, this->height(), output);
  }

  // double framerate = 12;
  if (this->framerate() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(12, this->framerate(), output);
  }

  // .camera.CaptureEncoding encoding = 13;
  if (this->encoding() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      13, this->encoding(), output);
  }

  // @@protoc_insertion_point(serialize_end:camera.StartCaptureArguments)
}

::google::protobuf::uint8* StartCaptureArguments::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:camera.StartCaptureArguments)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cameraName = 8;
  if (this->cameraname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cameraname().data(), this->cameraname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "camera.StartCaptureArguments.cameraName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->cameraname(), target);
  }

  // string cameraPath = 9;
  if (this->camerapath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->camerapath().data(), this->camerapath().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "camera.StartCaptureArguments.cameraPath");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->camerapath(), target);
  }

  // uint32 width = 10;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->width(), target);
  }

  // uint32 height = 11;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(11, this->height(), target);
  }

  // double framerate = 12;
  if (this->framerate() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(12, this->framerate(), target);
  }

  // .camera.CaptureEncoding encoding = 13;
  if (this->encoding() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      13, this->encoding(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:camera.StartCaptureArguments)
  return target;
}

size_t StartCaptureArguments::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera.StartCaptureArguments)
  size_t total_size = 0;

  // string cameraName = 8;
  if (this->cameraname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cameraname());
  }

  // string cameraPath = 9;
  if (this->camerapath().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->camerapath());
  }

  // .camera.CaptureEncoding encoding = 13;
  if (this->encoding() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->encoding());
  }

  // uint32 width = 10;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width());
  }

  // uint32 height = 11;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->height());
  }

  // double framerate = 12;
  if (this->framerate() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StartCaptureArguments::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera.StartCaptureArguments)
  GOOGLE_DCHECK_NE(&from, this);
  const StartCaptureArguments* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StartCaptureArguments>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera.StartCaptureArguments)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera.StartCaptureArguments)
    MergeFrom(*source);
  }
}

void StartCaptureArguments::MergeFrom(const StartCaptureArguments& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera.StartCaptureArguments)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.cameraname().size() > 0) {

    cameraname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cameraname_);
  }
  if (from.camerapath().size() > 0) {

    camerapath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.camerapath_);
  }
  if (from.encoding() != 0) {
    set_encoding(from.encoding());
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.framerate() != 0) {
    set_framerate(from.framerate());
  }
}

void StartCaptureArguments::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera.StartCaptureArguments)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StartCaptureArguments::CopyFrom(const StartCaptureArguments& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera.StartCaptureArguments)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StartCaptureArguments::IsInitialized() const {
  return true;
}

void StartCaptureArguments::Swap(StartCaptureArguments* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StartCaptureArguments::InternalSwap(StartCaptureArguments* other) {
  cameraname_.Swap(&other->cameraname_);
  camerapath_.Swap(&other->camerapath_);
  std::swap(encoding_, other->encoding_);
  std::swap(width_, other->width_);
  std::swap(height_, other->height_);
  std::swap(framerate_, other->framerate_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StartCaptureArguments::GetMetadata() const {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StartCaptureArguments

// string cameraName = 8;
void StartCaptureArguments::clear_cameraname() {
  cameraname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StartCaptureArguments::cameraname() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureArguments.cameraName)
  return cameraname_.GetNoArena();
}
void StartCaptureArguments::set_cameraname(const ::std::string& value) {
  
  cameraname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:camera.StartCaptureArguments.cameraName)
}
#if LANG_CXX11
void StartCaptureArguments::set_cameraname(::std::string&& value) {
  
  cameraname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:camera.StartCaptureArguments.cameraName)
}
#endif
void StartCaptureArguments::set_cameraname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  cameraname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:camera.StartCaptureArguments.cameraName)
}
void StartCaptureArguments::set_cameraname(const char* value, size_t size) {
  
  cameraname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:camera.StartCaptureArguments.cameraName)
}
::std::string* StartCaptureArguments::mutable_cameraname() {
  
  // @@protoc_insertion_point(field_mutable:camera.StartCaptureArguments.cameraName)
  return cameraname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StartCaptureArguments::release_cameraname() {
  // @@protoc_insertion_point(field_release:camera.StartCaptureArguments.cameraName)
  
  return cameraname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StartCaptureArguments::set_allocated_cameraname(::std::string* cameraname) {
  if (cameraname != NULL) {
    
  } else {
    
  }
  cameraname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cameraname);
  // @@protoc_insertion_point(field_set_allocated:camera.StartCaptureArguments.cameraName)
}

// string cameraPath = 9;
void StartCaptureArguments::clear_camerapath() {
  camerapath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StartCaptureArguments::camerapath() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureArguments.cameraPath)
  return camerapath_.GetNoArena();
}
void StartCaptureArguments::set_camerapath(const ::std::string& value) {
  
  camerapath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:camera.StartCaptureArguments.cameraPath)
}
#if LANG_CXX11
void StartCaptureArguments::set_camerapath(::std::string&& value) {
  
  camerapath_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:camera.StartCaptureArguments.cameraPath)
}
#endif
void StartCaptureArguments::set_camerapath(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  camerapath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:camera.StartCaptureArguments.cameraPath)
}
void StartCaptureArguments::set_camerapath(const char* value, size_t size) {
  
  camerapath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:camera.StartCaptureArguments.cameraPath)
}
::std::string* StartCaptureArguments::mutable_camerapath() {
  
  // @@protoc_insertion_point(field_mutable:camera.StartCaptureArguments.cameraPath)
  return camerapath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StartCaptureArguments::release_camerapath() {
  // @@protoc_insertion_point(field_release:camera.StartCaptureArguments.cameraPath)
  
  return camerapath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StartCaptureArguments::set_allocated_camerapath(::std::string* camerapath) {
  if (camerapath != NULL) {
    
  } else {
    
  }
  camerapath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camerapath);
  // @@protoc_insertion_point(field_set_allocated:camera.StartCaptureArguments.cameraPath)
}

// uint32 width = 10;
void StartCaptureArguments::clear_width() {
  width_ = 0u;
}
::google::protobuf::uint32 StartCaptureArguments::width() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureArguments.width)
  return width_;
}
void StartCaptureArguments::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureArguments.width)
}

// uint32 height = 11;
void StartCaptureArguments::clear_height() {
  height_ = 0u;
}
::google::protobuf::uint32 StartCaptureArguments::height() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureArguments.height)
  return height_;
}
void StartCaptureArguments::set_height(::google::protobuf::uint32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureArguments.height)
}

// double framerate = 12;
void StartCaptureArguments::clear_framerate() {
  framerate_ = 0;
}
double StartCaptureArguments::framerate() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureArguments.framerate)
  return framerate_;
}
void StartCaptureArguments::set_framerate(double value) {
  
  framerate_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureArguments.framerate)
}

// .camera.CaptureEncoding encoding = 13;
void StartCaptureArguments::clear_encoding() {
  encoding_ = 0;
}
::camera::CaptureEncoding StartCaptureArguments::encoding() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureArguments.encoding)
  return static_cast< ::camera::CaptureEncoding >(encoding_);
}
void StartCaptureArguments::set_encoding(::camera::CaptureEncoding value) {
  
  encoding_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureArguments.encoding)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StartCaptureResult::kCanResetGraphFieldNumber;
const int StartCaptureResult::kCanSetAudioConfigFieldNumber;
const int StartCaptureResult::kCanSetVideoConfigFieldNumber;
const int StartCaptureResult::kCanConnectFiltersFieldNumber;
const int StartCaptureResult::kResultFieldNumber;
const int StartCaptureResult::kDevicePointerFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StartCaptureResult::StartCaptureResult()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_proto_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera.StartCaptureResult)
}
StartCaptureResult::StartCaptureResult(const StartCaptureResult& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&canresetgraph_, &from.canresetgraph_,
    reinterpret_cast<char*>(&devicepointer_) -
    reinterpret_cast<char*>(&canresetgraph_) + sizeof(devicepointer_));
  // @@protoc_insertion_point(copy_constructor:camera.StartCaptureResult)
}

void StartCaptureResult::SharedCtor() {
  ::memset(&canresetgraph_, 0, reinterpret_cast<char*>(&devicepointer_) -
    reinterpret_cast<char*>(&canresetgraph_) + sizeof(devicepointer_));
  _cached_size_ = 0;
}

StartCaptureResult::~StartCaptureResult() {
  // @@protoc_insertion_point(destructor:camera.StartCaptureResult)
  SharedDtor();
}

void StartCaptureResult::SharedDtor() {
}

void StartCaptureResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StartCaptureResult::descriptor() {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StartCaptureResult& StartCaptureResult::default_instance() {
  protobuf_proto_2eproto::InitDefaults();
  return *internal_default_instance();
}

StartCaptureResult* StartCaptureResult::New(::google::protobuf::Arena* arena) const {
  StartCaptureResult* n = new StartCaptureResult;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StartCaptureResult::Clear() {
// @@protoc_insertion_point(message_clear_start:camera.StartCaptureResult)
  ::memset(&canresetgraph_, 0, reinterpret_cast<char*>(&devicepointer_) -
    reinterpret_cast<char*>(&canresetgraph_) + sizeof(devicepointer_));
}

bool StartCaptureResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera.StartCaptureResult)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool canResetGraph = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(112u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &canresetgraph_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool canSetAudioConfig = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(120u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &cansetaudioconfig_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool canSetVideoConfig = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(128u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &cansetvideoconfig_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool canConnectFilters = 17;
      case 17: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(136u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &canconnectfilters_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .camera.StartResult result = 18;
      case 18: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(144u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_result(static_cast< ::camera::StartResult >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 devicePointer = 19;
      case 19: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(152u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &devicepointer_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera.StartCaptureResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera.StartCaptureResult)
  return false;
#undef DO_
}

void StartCaptureResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera.StartCaptureResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool canResetGraph = 14;
  if (this->canresetgraph() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(14, this->canresetgraph(), output);
  }

  // bool canSetAudioConfig = 15;
  if (this->cansetaudioconfig() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(15, this->cansetaudioconfig(), output);
  }

  // bool canSetVideoConfig = 16;
  if (this->cansetvideoconfig() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(16, this->cansetvideoconfig(), output);
  }

  // bool canConnectFilters = 17;
  if (this->canconnectfilters() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(17, this->canconnectfilters(), output);
  }

  // .camera.StartResult result = 18;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      18, this->result(), output);
  }

  // uint64 devicePointer = 19;
  if (this->devicepointer() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(19, this->devicepointer(), output);
  }

  // @@protoc_insertion_point(serialize_end:camera.StartCaptureResult)
}

::google::protobuf::uint8* StartCaptureResult::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:camera.StartCaptureResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool canResetGraph = 14;
  if (this->canresetgraph() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(14, this->canresetgraph(), target);
  }

  // bool canSetAudioConfig = 15;
  if (this->cansetaudioconfig() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(15, this->cansetaudioconfig(), target);
  }

  // bool canSetVideoConfig = 16;
  if (this->cansetvideoconfig() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(16, this->cansetvideoconfig(), target);
  }

  // bool canConnectFilters = 17;
  if (this->canconnectfilters() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(17, this->canconnectfilters(), target);
  }

  // .camera.StartResult result = 18;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      18, this->result(), target);
  }

  // uint64 devicePointer = 19;
  if (this->devicepointer() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(19, this->devicepointer(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:camera.StartCaptureResult)
  return target;
}

size_t StartCaptureResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera.StartCaptureResult)
  size_t total_size = 0;

  // bool canResetGraph = 14;
  if (this->canresetgraph() != 0) {
    total_size += 1 + 1;
  }

  // bool canSetAudioConfig = 15;
  if (this->cansetaudioconfig() != 0) {
    total_size += 1 + 1;
  }

  // bool canSetVideoConfig = 16;
  if (this->cansetvideoconfig() != 0) {
    total_size += 2 + 1;
  }

  // bool canConnectFilters = 17;
  if (this->canconnectfilters() != 0) {
    total_size += 2 + 1;
  }

  // .camera.StartResult result = 18;
  if (this->result() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->result());
  }

  // uint64 devicePointer = 19;
  if (this->devicepointer() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->devicepointer());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StartCaptureResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera.StartCaptureResult)
  GOOGLE_DCHECK_NE(&from, this);
  const StartCaptureResult* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StartCaptureResult>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera.StartCaptureResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera.StartCaptureResult)
    MergeFrom(*source);
  }
}

void StartCaptureResult::MergeFrom(const StartCaptureResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera.StartCaptureResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.canresetgraph() != 0) {
    set_canresetgraph(from.canresetgraph());
  }
  if (from.cansetaudioconfig() != 0) {
    set_cansetaudioconfig(from.cansetaudioconfig());
  }
  if (from.cansetvideoconfig() != 0) {
    set_cansetvideoconfig(from.cansetvideoconfig());
  }
  if (from.canconnectfilters() != 0) {
    set_canconnectfilters(from.canconnectfilters());
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
  if (from.devicepointer() != 0) {
    set_devicepointer(from.devicepointer());
  }
}

void StartCaptureResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera.StartCaptureResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StartCaptureResult::CopyFrom(const StartCaptureResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera.StartCaptureResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StartCaptureResult::IsInitialized() const {
  return true;
}

void StartCaptureResult::Swap(StartCaptureResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StartCaptureResult::InternalSwap(StartCaptureResult* other) {
  std::swap(canresetgraph_, other->canresetgraph_);
  std::swap(cansetaudioconfig_, other->cansetaudioconfig_);
  std::swap(cansetvideoconfig_, other->cansetvideoconfig_);
  std::swap(canconnectfilters_, other->canconnectfilters_);
  std::swap(result_, other->result_);
  std::swap(devicepointer_, other->devicepointer_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StartCaptureResult::GetMetadata() const {
  protobuf_proto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StartCaptureResult

// bool canResetGraph = 14;
void StartCaptureResult::clear_canresetgraph() {
  canresetgraph_ = false;
}
bool StartCaptureResult::canresetgraph() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureResult.canResetGraph)
  return canresetgraph_;
}
void StartCaptureResult::set_canresetgraph(bool value) {
  
  canresetgraph_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureResult.canResetGraph)
}

// bool canSetAudioConfig = 15;
void StartCaptureResult::clear_cansetaudioconfig() {
  cansetaudioconfig_ = false;
}
bool StartCaptureResult::cansetaudioconfig() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureResult.canSetAudioConfig)
  return cansetaudioconfig_;
}
void StartCaptureResult::set_cansetaudioconfig(bool value) {
  
  cansetaudioconfig_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureResult.canSetAudioConfig)
}

// bool canSetVideoConfig = 16;
void StartCaptureResult::clear_cansetvideoconfig() {
  cansetvideoconfig_ = false;
}
bool StartCaptureResult::cansetvideoconfig() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureResult.canSetVideoConfig)
  return cansetvideoconfig_;
}
void StartCaptureResult::set_cansetvideoconfig(bool value) {
  
  cansetvideoconfig_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureResult.canSetVideoConfig)
}

// bool canConnectFilters = 17;
void StartCaptureResult::clear_canconnectfilters() {
  canconnectfilters_ = false;
}
bool StartCaptureResult::canconnectfilters() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureResult.canConnectFilters)
  return canconnectfilters_;
}
void StartCaptureResult::set_canconnectfilters(bool value) {
  
  canconnectfilters_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureResult.canConnectFilters)
}

// .camera.StartResult result = 18;
void StartCaptureResult::clear_result() {
  result_ = 0;
}
::camera::StartResult StartCaptureResult::result() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureResult.result)
  return static_cast< ::camera::StartResult >(result_);
}
void StartCaptureResult::set_result(::camera::StartResult value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureResult.result)
}

// uint64 devicePointer = 19;
void StartCaptureResult::clear_devicepointer() {
  devicepointer_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 StartCaptureResult::devicepointer() const {
  // @@protoc_insertion_point(field_get:camera.StartCaptureResult.devicePointer)
  return devicepointer_;
}
void StartCaptureResult::set_devicepointer(::google::protobuf::uint64 value) {
  
  devicepointer_ = value;
  // @@protoc_insertion_point(field_set:camera.StartCaptureResult.devicePointer)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace camera

// @@protoc_insertion_point(global_scope)
